# MyCustomManifest.yaml

scope: user
manifests:
  - name: Obsidian
    version: 1.0.0
    publisher: MyCompany
    installer:
      url: https://github.com/JoshuaAndersonRusk/winget-pkgs/raw/master/manifests/o/Obsidian/Obsidian/1.0.0/Obsidian.Obsidian.1.0.0.nupkg
      sha256: 6b1c2c4d7d6d7f6d7d6f7d6d7d6f7d6d7f6d7d6f7d6d7f6d7d6f7d6d7f6d7d6d
